import cv2
import pytesseract
import numpy as np

pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

def create_perfect_test_image():
    img = np.ones((200, 600, 3), dtype=np.uint8) * 255
    cv2.putText(img, "TEST OCR 100%", (50, 110), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0, 0), 5)
    cv2.imwrite("autogenerated_test.png", img)
    return "autogenerated_test.png"

def preprocess_image(image_path):
    img = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    return img, gray

def run_ocr(image_path):
    img, processed_img = preprocess_image(image_path)
    custom_config = r'--psm 6'
    ocr_data = pytesseract.image_to_data(processed_img, config=custom_config, output_type=pytesseract.Output.DICT)
    
    print("\n--- Starting OCR Extraction ---")
    full_text = []
    
    for i in range(len(ocr_data['text'])):
        text_chunk = ocr_data['text'][i].strip()
        if text_chunk != "":
            try:
                confidence = float(ocr_data['conf'][i])
            except ValueError:
                continue
                
            if confidence >= 50.0:  
                full_text.append(text_chunk)
                x, y, w, h = ocr_data['left'][i], ocr_data['top'][i], ocr_data['width'][i], ocr_data['height'][i]
                cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)
                cv2.putText(img, text_chunk, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
            
    print("Extracted Text:")
    print(" ".join(full_text))
    
    output_filename = "final_project_result.png"
    cv2.imwrite(output_filename, img)
    print(f"\nResult saved as: {output_filename}")
    print("--------------------------------------------------")
    
    cv2.imshow("Project 4 - Visual Confirmation", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

if __name__ == "__main__":
    test_file = create_perfect_test_image()
    run_ocr(test_file)